# Generated by Django 3.1.5 on 2021-02-03 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gemsdeals', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customers',
            new_name='Customer',
        ),
        migrations.RenameModel(
            old_name='Deals',
            new_name='Deal',
        ),
        migrations.RenameModel(
            old_name='Gems',
            new_name='Gem',
        ),
    ]
