# Generated by Django 3.1.5 on 2021-02-03 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gemsdeals', '0002_auto_20210203_0936'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gem',
            old_name='gems_name',
            new_name='gem_name',
        ),
    ]
