# Generated by Django 3.1.6 on 2021-02-04 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gemsdeals', '0005_menu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ('position',), 'verbose_name': 'Пункт меню', 'verbose_name_plural': 'Пункты меню'},
        ),
    ]
